name: Angular CI Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    strategy:
      matrix:
        node-version: [22]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Action to checkout your repository code

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }} # Specify the Node.js version suitable for your Angular project

      - name: Install Dependencies
        run: npm ci # Install project dependencies (using 'ci' for clean install in CI environments)

      - name: Build Angular Application
        run: npm run build -- --configuration=production # Build the Angular application for production
