name: Workflow de testes do projeto

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 # Action to checkout your repository code

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }} # Specify the Node.js version suitable for your Angular project

    - name: Install Dependencies
      run: npm ci # Install project dependencies (using 'ci' for clean install in CI environments)


      # Optional: Add steps for testing or deployment here
    - name: Run Unit Tests
      run: npm test -- --watch=false --browsers=ChromeHeadless