name: SpringBoot MicroServices CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:

  #test-project:
  #  uses: ./.github/workflows/tests.yml
  #  secrets: inherit

  build-project:
    #  needs: test-project
    uses: ./.github/workflows/angular-build.yml
    secrets: inherit

  #zap-scan:
  #  needs: build-project
  #  uses: ./.github/workflows/zap_scan.yml
  #  secrets: inherit

  #docker:
  #  needs: zap-scan
  #  uses: ./.github/workflows/Docker.yml
  #  secrets: inherit
  
  #deploy_ecs:
  #  needs: docker
  #  uses: ./.github/workflows/ECS.yml
  #  secrets: inherit